version: '3.4'

services:
  helloworldnode:
    image: ${DOCKER_REGISTRY}/aks-helloworldnode:${VERSION:-dev}
    build:
      context: .
      dockerfile: Services/HelloNode/Dockerfile
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./Services/hello-php/code:/code
        - ./Services/hello-php/site.conf:/etc/nginx/conf.d/default.conf
    networks:
        - code-network
  php:
    image: php:fpm
    volumes:
        - ./Services/hello-php/code:/code
    networks:
        - code-network

networks:
  code-network:
      driver: bridge
      