version: '3.4'

services:
  helloworldnode:
    image: ${DOCKER_REGISTRY}/aks-helloworldnode:${VERSION:-dev}
    build:
      context: .
      dockerfile: Services/HelloNode/Dockerfile
  web:
    image: ${DOCKER_REGISTRY}/aks-helloworldnginx:${VERSION:-dev}
    build:
      context: .
      dockerfile: Services/hello-php/Dockerfile
    ports:
        - "8080:80"
    # volumes:
    #     - ./Services/hello-php/code:/code
    #     - ./Services/hello-php/site.conf:/etc/nginx/conf.d/default.conf
    # networks:
    #     - code-network
  # php:
  #   image: ${DOCKER_REGISTRY}/aks-helloworldphp:${VERSION:-dev}
  #   build:
  #     context: .
  #     dockerfile: Services/hello-/Dockerfile
  #   volumes:
  #       - ./Services/hello-php/code:/code
  #   networks:
  #       - code-network

# networks:
#   code-network:
#       driver: bridge
      