version: '3.4'

services:

  #PHP Service
  app:
    image: ${DOCKER_REGISTRY}/aks-hellolaravel:${VERSION:-dev}
    build:
      context: .
      dockerfile: Services/HelloLaravel/Dockerfile
    # image: digitalocean.com/php
    container_name: app_k8s
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_k8s
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_k8s
    restart: unless-stopped
    tty: true
    ports:
      - "8008:80"
        #  - "4431:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.17
    container_name: db_k8s
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root@123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local 

